Lang processor interlayer
PhantomYdn/wicket-console pull request #5
Opened 2016-10-27 11:14 UTC by SergeyAsm

added script engine interlayer

2016-10-27 17:30 UTC, PhantomYdn requested changes

2016-10-27 17:30 UTC, PhantomYdn commented on wicket-console/pom.xml
> +    		<dependency>
See previous PR for comments about dependencies.

2016-10-27 17:30 UTC, PhantomYdn commented on wicket-console/src/main/java/ru/ydn/wicket/wicketconsole/IScriptEngineInterlayer.java
> +	IScriptEngineInterlayerResult eval(String command) throws Exception;
Is context saving somewhere?

2016-10-27 17:30 UTC, PhantomYdn commented on wicket-console/src/main/java/ru/ydn/wicket/wicketconsole/ScriptEngineInterlayerManager.java
> +		interlayers = new HashMap<String,IScriptEngineInterlayer>();
If I understood this correctly: execution context will be the same for all users who is working in parallel. And that's definetly wrong.

2016-10-28 06:51 UTC, SergeyAsm commented on wicket-console/src/main/java/ru/ydn/wicket/wicketconsole/ScriptEngineInterlayerManager.java
> +		interlayers = new HashMap<String,IScriptEngineInterlayer>();
Mea culpa )

2016-10-28 07:00 UTC, SergeyAsm commented on wicket-console/src/main/java/ru/ydn/wicket/wicketconsole/IScriptEngineInterlayer.java
> +	IScriptEngineInterlayerResult eval(String command) throws Exception;
just IDE trash

2016-11-07 01:49 UTC, PhantomYdn approved these changes

2017-01-06 23:38 UTC, PhantomYdn commented
Merged separatly from this PR

2017-01-06 23:38 UTC, closed without merging